apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: grpc-cue-envoy-rbac
build:
  artifacts:
  - image: example
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOOGLE_BUILDABLE=./cmd/example
      dependencies:
        paths:
        - cmd/**
        - internal/**
        - pkg/**
        - go.*
  - image: authorization
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOOGLE_BUILDABLE=./cmd/authorization
      dependencies:
        paths:
        - cmd/**
        - internal/**
        - pkg/**
        - go.*
  - image: rbac
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOOGLE_BUILDABLE=./cmd/rbac
      dependencies:
        paths:
        - cmd/**
        - internal/**
        - pkg/**
        - go.*
  - image: reflection
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOOGLE_BUILDABLE=./cmd/reflection
      dependencies:
        paths:
        - cmd/**
        - internal/**
        - pkg/**
        - go.*
deploy:
  kustomize:
    paths:
    - deployments
portForward:
- resourceType: service
  resourceName: example
  port: 9000
  localPort: 9000
- resourceType: service
  resourceName: envoy
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: authorization
  port: 9001
  localPort: 9001
- resourceType: service
  resourceName: rbac
  port: 9002
  localPort: 9002
- resourceType: service
  resourceName: reflection
  port: 9003
  localPort: 9003
