name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Install protoc
      run: |
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-linux-x86_64.zip \
          && sudo unzip protoc-${PROTOC}-linux-x86_64.zip -d /usr/local \
          && sudo chmod +x /usr/local/bin/protoc \
          && rm protoc-${PROTOC}-linux-x86_64.zip
      env:
        PROTOC: 3.20.1
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get -y install --no-install-recommends clang-format
    # https://github.com/actions/setup-go/issues/130
    # https://github.com/actions/cache/blob/main/examples.md#go---modules
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Install go deps
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - run: make
    - run: git diff --exit-code
